DROP TABLE HISTORICO_PRUEBA;
DROP TABLE PRUEBA;
DROP TABLE VERSION;
DROP TABLE APP;
DROP TABLE TIPO_APP;
DROP TABLE TIPO_PRUEBA;
DROP TABLE ESTADO_PRUEBA;
DROP TABLE SCRIPT;

CREATE TABLE SCRIPT (
  idScript SERIAL PRIMARY KEY,
  descripcion VARCHAR(50),
  contenido VARCHAR(200)
);

CREATE TABLE ESTADO_PRUEBA (
  idEstado SERIAL PRIMARY KEY,
  descripcion VARCHAR(50)
);

CREATE TABLE TIPO_PRUEBA(
  idTipo SERIAL PRIMARY KEY,
  descripcion VARCHAR(50),
  parametros VARCHAR(50),
  script INTEGER NOT NULL,
  CONSTRAINT script_fkey FOREIGN KEY (script)
  REFERENCES SCRIPT (idScript) MATCH SIMPLE
  ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE TIPO_APP(
  idTipoApp SERIAL PRIMARY KEY,
  descripcion VARCHAR(50)
);

CREATE TABLE APP(
  idApp SERIAL PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL,
  tipoApp INTEGER NOT NULL,
  CONSTRAINT tipoApp_fkey FOREIGN KEY (tipoApp)
    REFERENCES TIPO_APP (idTipoApp) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE VERSION(
  idVersion SERIAL PRIMARY KEY,
  descripcion VARCHAR(50),
  rutaApp VARCHAR(100),
  app INTEGER NOT NULL,
  CONSTRAINT app_fkey FOREIGN KEY (app)
    REFERENCES APP (idApp) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE PRUEBA(
  idPrueba SERIAL PRIMARY KEY,
  tipo INTEGER NOT NULL,
  app INTEGER NOT NULL,
  CONSTRAINT tipo_fkey FOREIGN KEY (tipo)
    REFERENCES TIPO_PRUEBA (idTipo) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT app_fkey1 FOREIGN KEY (app)
    REFERENCES APP (idApp) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE HISTORICO_PRUEBA(
  idHis SERIAL PRIMARY KEY,
  prueba INTEGER NOT NULL,
  estado INTEGER NOT NULL,
  fechaInicio TIMESTAMP,
  fechaFin TIMESTAMP,
  CONSTRAINT prueba_fkey FOREIGN KEY (prueba)
    REFERENCES PRUEBA (idPrueba) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT estado_fkey FOREIGN KEY (estado)
    REFERENCES ESTADO_PRUEBA (idEstado) MATCH SIMPLE
    ON UPDATE NO ACTION ON DELETE NO ACTION
);
